name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        id: build-image
        run: |
          # Build the Docker image from the Dockerfile in your repository
          docker buildx build --platform linux/amd64,linux/arm64 -t alpha-os:staged .
          # Start the Docker container from the built image
          docker run --name alpha-os-container -d alpha-os:staged
          docker cp $(docker ps -q -f ancestor=alpha-os:staged):/alpha_os/isodir/os.iso ./os.iso
          docker ps -a
        continue-on-error: true

      - name: Start Docker container
        if: steps.build-image.outcome == 'success'
        run: docker run --name alpha-os-container -d alpha-os:staged

      - name: Export Docker image
        if: steps.build-image.outcome == 'success'
        run: docker save alpha-os:staged > alpha-os.tar

      - name: Copy ISO to host
        run: docker cp $(docker ps -q -f ancestor=alpha-os:staged):/alpha_os/isodir/os.iso ./os.iso
        if: steps.build-image.outcome == 'success'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: alpha-os.tar
        if: steps.build-image.outcome == 'success'
